### PR TITLE
Be more explicit with ssh_host_keys perms

### LINKED ISSUE #95: [BUG] [9.7_p1-r4-ls174] is broken, sshd not started
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

sshd not started in the latest image [9.7_p1-r4-ls174] but old image [9.7_p1-r4-ls173] works fine. 

### Expected Behavior

sshd started. 

### Steps To Reproduce

1. pull the latest image
2. start the docker with docker-compose up
3. terminal shows "sshd is listening on port 2222"
4. but sshd is not running (can be verified by docker exec -it)

### Environment

```markdown
- OS:Debian 12
- How docker service was installed: 
deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian   bookworm stable
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  openssh-server:
    #image: lscr.io/linuxserver/openssh-server:9.7_p1-r4-ls173
    image: lscr.io/linuxserver/openssh-server
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PUBLIC_KEY_DIR=/config/pub_keys
      - SUDO_ACCESS=false #optional
      - PASSWORD_ACCESS=false #optional
      - USER_NAME=xxxx
    volumes:
      - /somefolder/sshd:/config
    ports:
      - XXXX:2222
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: 9.7_p1-r4-ls174
Build-date: 2024-11-22T16:51:16+00:00
───────────────────────────────────────

User name is set to xxxx
sudo is disabled.
SSH host public key(s):
ssh-dss AAAAB3Nza...k0M= root@openssh-server
ecdsa-sha2-nistp256 AAAAE2...Q0KjA8= root@openssh-server
ssh-ed25519 AAAAC...maExsw6aAX root@openssh-server
ssh-rsa AAAAB3...WbBU= root@openssh-server
sshd is listening on port 2222
User/password ssh access is disabled.
[custom-init] No custom files found, skipping...
```

### PR DESCRIPTION
**Pull request by thespad**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-openssh-server/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
Closes #95

### CODE REVIEW

**Review by Roxedus — APPROVED** [review]

File: root/etc/s6-overlay/s6-rc.d/init-openssh-server-config/run [hunk 1]
```diff
@@ -132,5 +132,13 @@ chmod 700 \
     /config/.ssh
 chmod 600 \
     /config/.ssh/authorized_keys
-chown root:root \
+
+# ssh_host_keys permissions
+lsiown -R root:root \
+    /config/ssh_host_keys
```
Comment (ionos) [inline root/etc/s6-overlay/s6-rc.d/init-openssh-server-config/run:138]: Apologies if I'm way off - why not leave it as "${USER_NAME}":"${USER_NAME}" and possibly 700/750? In cases where /config is an external volume mounted into the container with stricter permissions, this would widen the perms.

Comment (thespad) [reply root/etc/s6-overlay/s6-rc.d/init-openssh-server-config/run:138]: Because a persistent complaint about this image is the ability for a connected user to modify the sshd_config, which would take effect on a container restart. You can't just chown sshd_config to root because an unprivileged user can still overwrite it with their own file.

Another option might be chown the folder and sshd_config to root but leave the host keys owned by the running user. This has the advantage of not having to change the permissions on the host keys but the permissions on the folder and config would still need to be world readable.

Comment (ionos) [reply root/etc/s6-overlay/s6-rc.d/init-openssh-server-config/run:138]: Got it, thanks for clarifying. Would it work to chown the sshd_config/folder to root:${USER_NAME} with 640/750 permissions?

Comment (thespad) [reply root/etc/s6-overlay/s6-rc.d/init-openssh-server-config/run:138]: Possibly, I'll test and see
